# build and deploy
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        n
      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: docs/.vuepress/dist/

